sonar.projectKey=TeamShiksha_openlogo
sonar.organization=teamshiksha
sonar.projectName=openlogo
sonar.coverage.exclusions=.github/**,*.yml,packages/*/Dockerfile
sonar.cpd.exclusions=packages/*/__tests__/**
