name: Check linting, format and test cases

on:
  workflow_dispatch:
  pull_request: 
    branches: 
      - dev
    paths:
      - 'packages/**'

jobs:
  test:
    name: Check linting/formatin and test cases
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: echo
        run: echo {{ github.event.pull_request.changed_files }}

      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 
        with:
            version: 10

      - name: Install run dependencies
        run: pnpm install

      - name: linting
        run: pnpm lint

      - name: prettier check
        run: pnpm check

      - name: frontend coverage report
        if: contains(github.event.pull_request.changed_files, 'packages/ui/')
        run: pnpm --filter ui coverage
      
      - name: backend coverage report
        if: contains(github.event.pull_request.changed_files, 'packages/app/')
        run: pnpm --filter app coverage
